# Generated by roxytest: Do not edit by hand!

context("File R/doer.R: @testexamples")

test_that("Function sankey() @ L97", {
  
  
  {
  sankey(x = example1, fig_title = "Boom?", sankey_color = "lightblue", sankey_label = "the whole system")
  }
})

